version: '3.8'

services:
  danmaku-task-monitor:
    build: .
    container_name: danmaku-task-monitor
    restart: unless-stopped
    
    # 数据和日志持久化
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      # 弹幕服务API必填配置
      - API_BASE_URL=弹幕服务API基础地址
      - API_KEY=弹幕服务API密钥
      
      # Telegram通知必填配置
      - TELEGRAM_BOT_TOKEN=Telegram机器人Token
      - TELEGRAM_CHAT_ID=接收通知的聊天ID
      
      # 时区配置（可选，默认Asia/Shanghai）
      - TZ=Asia/Shanghai
      
      # 检查间隔(秒)，默认60秒
      - CHECK_INTERVAL=60
      # 时间窗口缓冲(秒)，默认60秒
      - TIME_WINDOW_BUFFER=60
      # 每次最多处理的任务数，默认50个
      - MAX_TASKS_TO_PROCESS=50
      - LOG_LEVEL=INFO
      # 日志文件保留天数，默认为7天
      - LOG_BACKUP_COUNT=7
      # 已处理任务ID列表最大大小，默认为1000
      - MAX_PROCESSED_TASKS=1000
    
    healthcheck:
      test: ["CMD", "python", "-m", "src.main", "--help"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s